### ISSUE TITLE
jlog?

### ISSUE THREAD

**Issue by richo67** [AgentZombie/wowlua#1] opened 2021-10-09 17:35 UTC
Jason (@jasonmf),
I had no idea how to contact you, but I am trying this code of your to parse some lua structures. I can not find out where to get the jlog package you using for logging. Thank you for you kind help.

-r- @

**Comment by SelfDrivingCarp** [comment] 2021-10-10 15:27
I was fairly new to Go when I created this package and I thought I needed clever logging, so I created a logging package `jlog`. That wasn't actually clever, nor was it a particularly good logging package. I'll update `wowlua` to not need it.

**Comment by richo67** [comment] 2021-10-10 18:56
Jason, do you still have your jLog module? Do you plan to change its use for something else or remove it at all?

**Comment by SelfDrivingCarp** [comment] 2021-10-10 19:03
I don't. It was mostly for debug messages. I've already started a commit to update this package. I should have it up by tomorrow night.

If you don't want to wait you could just delete all the `jlog` references in a local copy and then use a `replace` in your `go.mod` to point to your local copy.

**Comment by richo67** [comment] 2021-10-11 06:36
Jason, thank you very much. I hope this didn't use too much of your time. I really appreciate your help.

I am learning `go` so some of the things, especially those who changed between the books I use and current state, confuses me a bit. I am referring to `.mod`, packages and their use and build.

**Comment by SelfDrivingCarp** [comment] 2021-10-11 20:44
https://github.com/jasonmf/wowlua/releases/tag/v0.2.1 adds a simple built-in logger, code documentation, a license (MIT) and a README. https://pkg.go.dev/github.com/jasonmf/wowlua hasn't picked the new version yet.

Have a look at the README and let me know if this works better for you.

**Comment by richo67** [comment] 2021-10-12 16:03
Thank you very much for your help, especially for your time and quick reaction.

**Comment by richo67** [comment] 2021-10-12 16:08
Now I have one more question.
I have file (see attachment) which I try to parse using your parse_demo/main.go, but getting:

 `error parsing: Ending table while not in table!`

Is the format of that lua file not what your parser is expecting?

[test.zip](https://github.com/jasonmf/wowlua/files/7331533/test.zip)

**Comment by SelfDrivingCarp** [comment] 2021-10-13 02:33
I took a brief look at it but I don't know what the issue is. It should be correctly dealing with the first line comment. I tried removing the `return` because I think I wrote it to expect a raw, literal table but the same issue. The error tells me it's hitting a closing brace that it's not expecting but I'm not seeing that in the data. I only wrote it to parse the Lua tables that World of Warcraft would persist and it may not be complete enough to handle all valid representations of Lua tables. I don't work with Lua and I no longer play WoW so I'm not going to try to fix the issue. Sorry!

**Comment by richo67** [comment] 2021-10-13 09:19
Jason, thank you to fix the jlog. Few last things:

- How to turn the debug printing on in your new logging? 
   - excuse me if that is trivial
- I have found out that the error I mentioned previously is caused by "," just before closing "}"
   - trying to figure that out, but as I wrote I am just beginner so the debug would help me to understand your code

Thank you for your patience with me.

**Comment by richo67** [comment] 2021-10-13 13:21
Jason,
I think I have manage to fix the issue when comma is not used at thee end of array. Not sure how to fully test it, but from the try outs I did it seems to be working in both cases with comma and without comma just before closing `'}'`
I hope I could help, if not you (as you mentioned not to use this anymore), than maybe somebody like me looking for a go library to parse lua data.
Thanks for your support !


<pre>
diff --git a/parse.go b/parse.go
index ea8f1ab..9d313bb 100644
--- a/parse.go
+++ b/parse.go
@@ -116,7 +116,24 @@ func (p *Parser) Next(t *Token) error {
        case TokenTypeEndTable:
                top := p.Peek()
                if top.nType != NodeTypeTable {
-                       return p.bailout("Ending table while not in table!")
+                       v := p.Pop()
+                       top = p.Peek()
+                       if top.nType == NodeTypeTableEntry {
+                               if e, ok := top.value.(*tableEntry); ok {
+                                       p.Pop()
+                                       top = p.Peek()
+                                       if top.nType != NodeTypeTable {
+                                               return p.bailout("Key not in table, when closing the table!")
+                                       }
+                                       if table, ok := top.value.(*Table); ok {
+                                               table.Set(e.key, v)
+                                       } else {
+                                               return p.bailout("Expected table node on top of stack.")
+                                       }
+                               } else {
+                                       return p.bailout("TableEntryValue not tableEntry!")
+                               }
+                       }
                }
        case TokenTypeStartKey:
                if p.Peek().nType != NodeTypeTable {
</pre>

**Comment by SelfDrivingCarp** [comment] 2021-10-14 02:19
I didn't actually provide a way to set debug logging without modifying the source. This was pure laziness and not any kind of thoughtful design.

If this PR gives you the results that you're looking for, I'm happy to merge it. I do think it should include a unit test that verifies the new behavior:

```
func TestTableTrailingComma(t *testing.T) {
        t.Parallel()

        testLuaData = `
<literal lua table>
`
        table, err := ParseLua(testLuaData)
        if err != nil {
                t.Fatal("Unexpected error: ", err)
        }
        // verify the contents of the table are as expected.
}
```

I'm not sure anyone else has ever used this library, as indicated by this being issue #1. If you want, I'd be happy to just make your fork canonical and refer the poor souls who find this one to yours. I'm content either way.

**Closed as completed** 2021-10-19 04:43 UTC
